{% set name = "webauthn" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/webauthn-{{ version }}.tar.gz
  sha256: 94fc8265cccce88e1e43dc2008f3d8bb1f05fdd547246efa1be8ef684a6c3a7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - asn1crypto >=1.4.0
    - cbor2 >=5.4.2.post1
    - cryptography >=41.0.1
    - pydantic >=1.10.11
    - pyopenssl >=23.2.0

test:
  imports:
    - webauthn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/duo-labs/py_webauthn
  summary: Pythonic WebAuthn
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
