schema_version: 1

context:
  name: webauthn
  version: "3.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/webauthn-${{ version }}.tar.gz
  sha256: 324e54e1f6eeef486623b5d90df6fcd74ae04ff0c137d2b818a8f709b6ca3ab8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - pyasn1 >=0.6.2
    - pyasn1-modules >=0.4.2
    - cbor2 >=5.6.5,<6.0.0
    - cryptography >=46.0.0
    - pyopenssl >=26.0.0

tests:
  - python:
      imports:
        - webauthn
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Pythonic WebAuthn
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/duo-labs/py_webauthn

extra:
  recipe-maintainers:
    - thewchan
